=== mosra/absencoid/absencoid/absencoid.dtd
<!-- Kořenový element absencoid, může být buď dump nebo update -->
<!ELEMENT absencoid (dump | update)>
<!ATTLIST absencoid xmlns CDATA #FIXED "http://mosra.bloguje.cz/absencoid/">
    <!-- Atributy: xmlns - sepcifikace namespace -->

<!-- Struktura pro dump -->
<!ELEMENT dump (date, configuration, teachers, classes, timetables, changes, absences)>
<!ATTLIST dump version CDATA #REQUIRED>
    <!-- Atributy: version - verze dumpu (proti konfliktu s novějšími verzemi programu -->
<!ELEMENT date (#PCDATA)>               <!-- Datum aktualizace (ve tvaru YYYY-MM-DD) -->

<!-- Struktura pro aktualizaci -->
<!ELEMENT update (date, note, configuration, teachers, classes, timetables, changes)>
<!ATTLIST update version CDATA #REQUIRED>
    <!-- Atributy: version - verze aktualizace (proti konfliktu s novějšími verzemi programu -->
<!-- ELEMENT date  -->                  <!-- Datum aktualizace (viz <dump>) -->
<!ELEMENT note (#PCDATA)>               <!-- Krátký popisek k aktualizaci -->

<!-- Konfigurace (tj. vše, co nepasuje jinam) -->
<!ELEMENT configuration (beginDate, endDate, webUpdateUrl, (lastUpdate, updateOnStart, dumpOnExit)?)>
<!ELEMENT beginDate (#PCDATA)>          <!-- Začátek pololetí (datum ve tvaru YYYY-MM-DD) -->
<!ELEMENT endDate (#PCDATA)>            <!-- Konec pololetí (datum ve tvaru YYYY-MM-DD) -->
<!ELEMENT webUpdateUrl (#PCDATA)>       <!-- URL pro provádění aktualizací z internetu -->
<!ELEMENT lastUpdate (#PCDATA)>         <!-- Datum poslední aktualizace -->
<!ELEMENT updateOnStart EMPTY>          <!-- Zda zjišťovat aktualizace po startu -->
<!ATTLIST updateOnStart value (true|false) #REQUIRED>
    <!-- Atributy: value - Boolean hodnota -->
<!ELEMENT dumpOnExit EMPTY>             <!-- Zda zálohovat data při ukončení programu -->
<!ATTLIST dumpOnExit value (true|false) #REQUIRED>
    <!-- Atributy: value - Boolean hodnota -->

<!-- Učitelé -->
<!ELEMENT teachers (teacher*)>
<!ELEMENT teacher (#PCDATA)>            <!-- Obsah: jméno učitele -->
<!ATTLIST teacher
    id ID #REQUIRED
    counts (true|false) #REQUIRED
    accepts (true|false) #REQUIRED
> <!-- Atributy:
    id          - unikátní ID učitele, např. p32
    counts      - zda počítá absence
    accepts     - zda uznává školní akce
-->

<!-- Předměty -->
<!ELEMENT classes (class*)>
<!ELEMENT class (#PCDATA)>              <!-- Obsah: jméno předmětu -->
<!ATTLIST class
    id ID #REQUIRED
    teacherId IDREF #REQUIRED
> <!-- Atributy:
    id          - unikátní ID předmětu s předponou 'c', např. c14
    teacherId   - reference na učitele, např. p32
-->

<!-- Rozvrhy -->
<!ELEMENT timetables (timetable*)>
<!ATTLIST timetables activeId IDREF #IMPLIED>
    <!-- ID aktivního rozvrhu, např t1. Pokud se jedná o aktualizaci, je tento
        parametr (ač povinný), ignorová, protože by měnil uživatelská data. -->
<!ELEMENT timetable (name, validFrom, data)>
<!ATTLIST timetable
    id ID #REQUIRED
    next IDREF #REQUIRED
> <!-- Atributy:
    id - ID rozvrhu s předponou 't', např. t1
    next - ID dalšího rozvrhu, např. t1
-->
<!ELEMENT name (#PCDATA)>               <!-- Jméno rozvrhu -->
<!ELEMENT validFrom (#PCDATA)>          <!-- Odkdy je rozvrh platný -->
<!-- TODO: Zrušit data? - konfliktní + nejednoznačný název -->
<!ELEMENT data (lesson*)>               <!-- Jednotlivé položky rozvrhu -->

<!ELEMENT lesson (day, hour)>           <!-- Vyučovací hodina -->
<!ATTLIST lesson
    classId IDREF #REQUIRED
    fixed (true|false) #REQUIRED
> <!-- Atributy:
    classId     - Reference na předmět, např. c14
    fixed       - Zda je předmět zamknutý, tj. může jej editovat jen správce.
                    Pokud je v aktualizaci nějaký předmět s fixed="false", je to
                    chyba, protože může změnit uživatelská data.
-->
<!ELEMENT day (#PCDATA)>                <!-- Den v týdnu (0 = pondělí) -->
<!ELEMENT hour (#PCDATA)>               <!-- Hodina (0 = nultá hodina) -->

<!-- Změny v rozvrhu -->
<!ELEMENT changes (change*)>
<!ELEMENT change (date, (hour | allHours), (fromClass | allClasses), toClass)>
    <!-- Změna může být buď z jedné hodiny nebo ze všech, z jednoho určitého
        předmětu (ovlivní jen určité rozvrhy) či ze všech -->
<!ATTLIST change id ID #REQUIRED>
    <!-- Atributy: id - ID změny s předponou 'x', např. x153 -->
<!-- ELEMENT date -->                   <!-- Datum změny (viz <dump>) -->
<!-- ELEMENT hour -->                   <!-- Hodina (viz <lesson>) -->
<!ELEMENT allHours EMPTY>               <!-- Všechny hodiny v tomto dni -->
<!ELEMENT fromClass EMPTY>              <!-- Předmět, ze kterého se mění -->
<!ATTLIST fromClass id IDREF #IMPLIED>
    <!-- Atributy: id - ID předmětu, např. c14. Pokud není uveden, myslí se prázdná hodina -->
<!ELEMENT allClasses EMPTY>             <!-- Všechny předměty -->
<!ELEMENT toClass EMPTY>                <!-- Předmět, na který se mění -->
<!ATTLIST toClass id IDREF #IMPLIED>
    <!-- Atributy: id - ID předmětu, např. c1. Pokud není uveden, myslí se prázdná hodina -->

<!-- Absence -->
<!ELEMENT absences (absence*)>
<!ELEMENT absence (date, (hour+ | allHours))>
    <!-- Absence může být buď jednotlivé hodiny nebo všechny hodiny v daném dni -->
<!ATTLIST absence id ID #REQUIRED>
    <!-- Atributy: id - ID absence s předponou 'a', např. a56 -->
<!-- ELEMENT date -->                   <!-- Datum absence (viz <dump>) -->
<!-- ELEMENT hour -->                   <!-- Hodina (viz <lesson>) -->
<!-- ELEMENT allHours -->               <!-- Všechny hodiny (viz <change>) -->

=== mosra/absencoid/absencoid/example-dump.xml
<?xml version="1.0" ?>

<!DOCTYPE absencoid SYSTEM "absencoid.dtd">

<absencoid xmlns="http://mosra.bloguje.cz/absencoid/">
    <dump version="1">
        <configuration>
            <beginDate>2009-09-07</beginDate>
            <endDate>2010-01-29</endDate>
            <webUpdateUrl>http://disk.jabbim.cz/mosra@jabbim.cz/absencoid-update.xml</webUpdateUrl>
            <updateOnStart value="false" />
            <dumpOnExit value="true" />
        </configuration>

        <teachers>
            <teacher id="p1" counts="false" accepts="true">Slušná</teacher>
            <teacher id="p2" counts="true" accepts="false">Zlá</teacher>
            <teacher id="p3" counts="true" accepts="true">Poctivý</teacher>
            <!-- ... -->
        </teachers>

        <classes>
            <class id="c1" teacherId="p1">Aj</class>
            <class id="c2" teacherId="p1">Nj</class>
            <class id="c3" teacherId="p1">F</class>
            <!-- ... -->
        </classes>

        <timetables activeId="t1">
            <timetable id="t1">
                <name>Hlavní rozvrh</name>
                <validFrom>2009-09-07</validFrom>
                <data>
                    <lesson classId="c1" fixed="true">
                        <day>0</day>
                        <hour>1</hour>
                    </lesson>
                    <lesson classId="c2" fixed="true">
                        <day>0</day>
                        <hour>2</hour>
                    </lesson>
                    <!-- Uživatelsky editovaná (tj. nepovinná) 0. hodina v úterý -->
                    <lesson classId="c3">
                        <day>1</day>
                        <hour>0</hour>
                    </lesson>
                    <!-- ... -->
                </data>
            </timetable>
            <!-- ... -->
        </timetables>

        <changes>
            <change id="x1">
                <!-- Tento den odpadají všechny hodiny -->
                <date>2009-09-07</date>
                <allHours />
                <allClasses />
                <toClass />
            </change>
            <change id="x2">
                <!-- V pondělí přibyla nultá hodina -->
                <date>2009-09-14</date>
                <hour>0</hour>
                <fromClass />
                <toClass id="c2" />
            </change>
            <change id="x3">
                <!-- V úterý máme další blbou hodinu místo flákací -->
                <date>2009-09-14</date>
                <hour>2</hour>
                <fromClass id="c1" />
                <toClass id="c2" />
            </change>
            <!-- ... -->
        </changes>

        <absences>
            <absence id="a1">
                <!-- Kdo by chodil do školy první den, že -->
                <date>2009-09-07</date>
                <allHours />
            </absence>
            <absence id="a2">
                <!-- Psali písemku z němčiny a chemie -->
                <date>2009-09-14</date>
                <hour>2</hour>
                <hour>4</hour>
            </absence>
            <!-- ... -->
        </absences>

    </dump>
</absencoid>

=== mosra/absencoid/absencoid/example-update.xml
<?xml version="1.0" ?>

<!DOCTYPE absencoid SYSTEM "absencoid.dtd">

<absencoid xmlns="http://mosra.bloguje.cz/absencoid/">
    <update version="1">
        <date>2009-07-25</date>

        <note>
            Vítejte! Právě stahujete první aktualizaci Absencoidu. Přidávám vám
            sem jeden rozvrh, pár předmětů a nějaké ty změny. Hákujte jak o život!
            Také se změnila adresa pro aktualizaci z internetu, protože ostatní
            aktualizace bude dělat konečně už někdo jiný než já.
        </note>

        <configuration>
            <beginDate>2009-09-07</beginDate>
            <endDate>2010-01-29</endDate>
            <webUpdateUrl>http://disk.jabbim.cz/mosra@jabbim.cz/absencoid-update.xml</webUpdateUrl>
        </configuration>

        <teachers>
            <teacher id="p1" counts="false" accepts="true">Slušná</teacher>
            <teacher id="p2" counts="true" accepts="false">Zlá</teacher>
            <teacher id="p3" counts="true" accepts="true">Poctivý</teacher>
            <!-- ... -->
        </teachers>

        <classes>
            <class id="c1" teacherId="p1">Aj</class>
            <class id="c2" teacherId="p1">Nj</class>
            <class id="c3" teacherId="p1">F</class>
            <!-- ... -->
        </classes>

        <timetables>
            <timetable id="t1" next="t1">
                <name>Hlavní rozvrh</name>
                <validFrom>2009-09-07</validFrom>
                <lessons>
                    <lesson classId="c1" fixed="true">
                        <day>0</day>
                        <hour>1</hour>
                    </lesson>
                    <lesson classId="c2" fixed="true">
                        <day>0</day>
                        <hour>2</hour>
                    </lesson>
                </lessons>
            </timetable>
            <!-- ... -->
        </timetables>

        <changes>
            <change id="x1">
                <!-- Tento den odpadají všechny hodiny -->
                <date>2009-09-07</date>
                <allHours />
                <allClasses />
                <toClass />
            </change>
            <change id="x2">
                <!-- V pondělí přibyla nultá hodina -->
                <date>2009-09-14</date>
                <hour>0</hour>
                <fromClass />
                <toClass id="c2" />
            </change>
            <change id="x3">
                <!-- V úterý máme další blbou hodinu místo flákací -->
                <date>2009-09-14</date>
                <hour>2</hour>
                <fromClass id="c1" />
                <toClass id="c2" />
            </change>
            <!-- ... -->
        </changes>

    </update>
</absencoid>
